### ISSUE TITLE
Missing file U54771.txt for unit test

### ISSUE THREAD

**Issue by donkirkby** [ArtPoon/gotoh2#13]
Looks like another file got missed. I've been happy with TravisCI as a way to make sure the test suite has all its dependencies in git. You just add a config file to call your tests and then register the repository with TravisCI. It runs the tests after every commit and sends you an e-mail if you broke something.

```
$ . runTests.sh 
.......E
======================================================================
ERROR: test_issue6 (test.TestIssues)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/data/don/git/gotoh2/tests/test.py", line 87, in test_issue6
    with open('U54771.txt') as f:
IOError: [Errno 2] No such file or directory: 'U54771.txt'

----------------------------------------------------------------------
Ran 8 tests in 0.334s

FAILED (errors=1)
```

**Comment by ArtPoon** [comment]
Dang it. You were right @donkirkby, I should at least add these sequences as test fixtures directly in the scripts.  Will fix.

**Comment by ArtPoon** [comment]
Converted all test sequences into fixtures.
