### ISSUE TITLE
Missing NL4-3.txt file in unit tests

### ISSUE THREAD

**Issue by donkirkby** [ArtPoon/gotoh2#9]
This is similar to issue #8, you're missing another file. You also still have the print output in your tests.

```
...
---AAAGGG---
TTAAAAGGGGTT
-14
..E.
======================================================================
ERROR: test_pol (test.TestHIV)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/data/don/git/gotoh2/tests/test.py", line 73, in test_pol
    with open('NL4-3.txt', 'rU') as f:
IOError: [Errno 2] No such file or directory: 'NL4-3.txt'

----------------------------------------------------------------------
Ran 7 tests in 0.002s

FAILED (errors=1)

```

In the test, it looks like you're just reading a single line from those two files. It might be easier to include two string literals in the test, then you don't have to worry about keeping track of the files.

**Comment by ArtPoon** [comment]
Ok, thanks.
Some of the tests are based on issues that require longer sequences and I didn't want to embed these as literals in the test scripts, but you're probably right.
